---
title: "Conflict and Ebola in DRC"
author: "Eugene Joh"
date: "October 29, 2018"
output: html_document
---

```{r setup, include=TRUE}
if (!require(here)) install.packages("here")
library(here)

library(knitr)
library(kableExtra)
knitr::opts_chunk$set(echo = TRUE, eval = TRUE, fig.height = 8, fig.width = 8.5)

# Load packages
source(here::here("00_load_packages.R"))
```

```{r load_fnc, include=TRUE}
source(here::here("R", "describe_df.R"))
```

# Data Import
```{r import, message=FALSE, warning=FALSE ,include=TRUE}
source(here::here("01_data_import.R"))
```

# Data Structure
## DRC Conflict
```{r drc_describe}
describe_df(d_drc) %>% 
  kable(caption = "Missing Values in 'd_drc' Data Frame") %>% 
  kable_styling(bootstrap_options = c("striped", "responsive"),
                position = "center")
```

```{r drc_datatype}
type_df(d_drc) %>% 
  kable(caption = "Variable Data Types for 'd_drc'") %>% 
  kable_styling(bootstrap_options = c("striped", "responsive"),
                position = "center")
```

```{r drc_describe_p}
left_join(describe_df(d_drc),
          type_df(d_drc),
          by = "col_name") %>% 
  ggplot(aes(x = col_name, y = NA_percent, fill = data_type, colour = data_type)) +
  geom_bar(stat='identity') +
  coord_flip() +
  labs(title = "Data Type and NA Values in DRC Conflict Data",
       x = "Variables", y = "Percent Missing (%)") +
  scale_fill_brewer(type = "qual", palette = 6, name = "Data Type") +
  scale_colour_brewer(type = "qual", palette = 6, guide = FALSE)
```

## Ebola Conflict
```{r evd_describe}
describe_df(d_evd) %>% 
  kable(caption = "Missing Values in 'd_evd' Data Frame") %>% 
  kable_styling(bootstrap_options = c("striped", "responsive"),
                position = "center")

```

```{r evd_datatype}
type_df(d_evd) %>% 
  kable(caption = "Variable Data Types for 'd_evd'") %>% 
  kable_styling(bootstrap_options = c("striped", "responsive"),
                position = "center")
```

```{r evd_describe_p}
left_join(describe_df(d_evd),
          type_df(d_evd),
          by = "col_name") %>% 
  ggplot(aes(x = col_name, y = NA_percent, fill = data_type, colour = data_type)) +
  geom_bar(stat='identity') +
  coord_flip() +
  labs(title = "Data Type and NA Values in DRC Ebola Case Data",
       x = "Variables", y = "Percent Missing (%)") +
  scale_fill_brewer(type = "qual", palette = 6, name = "Data Type") +
  scale_colour_brewer(type = "qual", palette = 6, guide = FALSE)
```

<br>
<br>

I'm sure there's a much better way to do this. Filtering by index is the only thing that seemed to work because I'm reaaaal bad at this. 

```{r evd_missing, results='asis'}
for (item in colnames(d_evd)[colSums(is.na(d_evd)) > 0]) {
  missing <- d_evd %>% select(item, publication_date, source)
  missing <- filter(missing, is.na(missing[1])) %>% unique()
  print(kable(missing, caption = paste("missing data:", item)) %>%
          kable_styling(full_width = F, position = "left"))
  cat('\n')
}

```


### Descriptors: 
```{r evd_eda}
source(here::here("exploratory_scripts", "ebola_descriptors.R"))
province_healthzone %>% 
  kable(caption = "Affected Health Zones") %>%
  kable_styling(full_width = F, position = "left")
epi_curve
```
**Date Range:** `r report_date_range`

<br>
<br>
<br>
<br>

**R Session Information: **
```{r rsessioninfo, echo=FALSE}
sessionInfo()
```

**Last Edited:** `r format(Sys.Date(), "%b %d %Y")`



